export const stockData = [
    {
      id: 0,
      company: "New Company",
      ticker: "NCY",
      stockPrice: "22.76 USD",
      timeElapsed: "5 sec ago",
      rightAnswer: "NCY",
    },
    {
      id: 1,
      company: "Monsters Org",
      ticker: "MO",
      stockPrice: "45.28 USD",
      timeElapsed: "10 sec ago",
      rightAnswer: "45.28 USD",
    },
    {
      id: 2,
      company: "New Space",
      ticker: "NS",
      stockPrice: "341.79 USD",
      timeElapsed: "3 sec ago",
      rightAnswer: "NS",
    },
    {
      id: 3,
      company: "Spin L",
      ticker: "SL",
      stockPrice: "9.87 USD",
      timeElapsed: "4 sec ago",
      rightAnswer: "4 sec ago",
    },
    {
      id: 4,
      company: "Wonder World",
      ticker: "WW",
      stockPrice: "300.99 USD",
      timeElapsed: "10 sec ago",
      rightAnswer: "WW",
    },
    {
      id: 5,
      company: "Wide World of Wrestling",
      ticker: "WWOW",
      stockPrice: "115.22 USD",
      timeElapsed: "12 sec ago",
      rightAnswer: "115.22 USD",
    },
  ];